
logging.file.name=logs/app.log
spring.web.resources.add-mappings=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:file:C:/datos/h2/testdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ============================
# PERFIL PARA DECIDIR SI USAMOS JPA O BBDD CUSTOMER (jpa,customer)
# ============================

spring.profiles.active=jpa

# ============================
# JWT CONFIG
# ============================

# Debe tener al menos 32 bytes (muy importante para HS256)
jwt.secret=CAMBIA_ESTE_SECRET_POR_UNO_REALMENTE_LARGO_Y_SEGURO_1234567890_ABCDEFGH

# Expiración del token en minutos
jwt.expiration-minutes=20

# ============================
# SEGURIDAD HABILITADA O NO
# ============================

security.enabled=false